### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by jbeguna04** [NasiaKouts/Baking-App#1]
Hello @NasiaKouts , Greetings!
Im a graphics designer and I would like to ask for your permission to propose logo/icon design for your project. I would like to help your project through this issue. Hoping for your response. Thank You!

Best Regards,
-jbeguna04

**Comment by NasiaKouts** [comment]
Hello,
sure! It's great you want to do this.
I am looking forward to check them out as soon as they are ready! 
Thank you in advance!
Nasia K

**Comment by jbeguna04** [comment]
![baking-app](https://user-images.githubusercontent.com/35353768/43517212-7c51e7a6-95ba-11e8-8eb8-cb7c74538fd5.png)
Here is my design for your project. What do you think?

**Comment by jbeguna04** [comment]
What do you think?

**Comment by NasiaKouts** [comment]
They are really amazing thank you!!!
The only thing I would prefer is if it is possible to rename it from baking app to baking recipes?

Other than that it is great!! Could you make a pull request with svg files of the brown logo mark and the (renamed) brown logo type?

**Comment by jbeguna04** [comment]
Sure I will. Thank you for your responses

**Comment by NasiaKouts** [comment]
You are welcome :) great job once again!

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/44001313-310c9524-9e62-11e8-9c3e-6c3f99d5766c.png)

Here is the one you have requested. What do you think?

**Comment by NasiaKouts** [comment]
Great!! It's perfect, thanks!
Feel free to make the pull request with the svg files.
